# Generated by Django 5.2 on 2025-04-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='title',
            new_name='description',
        ),
    ]
